---
- name: 'Setup MicroOS servers'
  hosts: 'servers'
  become: true
  handlers:
    - name: 'Reboot'
      ansible.builtin.reboot:
  tasks:
    - name: 'Set hostname to inventory hostname'
      ansible.builtin.hostname:
        name: '{{ inventory_hostname }}'

    - name: 'Clear contents of /var/lib/zypp/AnonymousUniqueId'
      ansible.builtin.copy:
        dest: '/var/lib/zypp/AnonymousUniqueId'
        content: ''
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: 'Set timezone to UTC'
      ansible.builtin.file:
        src: '../usr/share/zoneinfo/Etc/UTC'
        dest: '/etc/localtime'
        state: 'link'
        force: true

    - name: 'Allow passwordless sudo'
      ansible.builtin.copy:
        content: '%wheel        ALL=(ALL)       NOPASSWD: ALL'
        dest: '/etc/sudoers.d/passwordless'
        owner: 'root'
        group: 'root'
        mode: '0440'

    - name: 'Refresh zypper metadata'
      ansible.builtin.command:
        argv:
          - 'zypper'
          - '--non-interactive'
          - 'refresh'
      changed_when: false

    - name: 'Install required packages'
      community.general.zypper:
        name:
          - 'system-group-wheel'
          - 'bash-completion'
          - 'python3'
        state: 'present'
      notify:
        - 'Reboot'

    - name: 'Apply pending reboot before continuing'
      ansible.builtin.meta: 'flush_handlers'

    - name: 'Run hardening role'
      ansible.builtin.include_role:
        name: 'hardening'
        apply:
          tags:
            - 'hardening'
      tags:
        - 'hardening'

    - name: 'Run gateway role'
      ansible.builtin.import_role:
        name: 'gateway'
      when: "inventory_hostname == 'gateway'"

    - name: 'Run podman role'
      ansible.builtin.import_role:
        name: 'podman'
      when: "inventory_hostname == 'miniserver'"
      tags:
        - 'podman'
