---
- name: 'Register Autopush service manifest'
  vars:
    autopush_manifest:
      quadlet_files:
        - src: 'autopush/haproxy-autopush.network'
          dest: 'haproxy-autopush.network'
          restart_units:
            - 'haproxy.service'
            - 'autoconnect.service'
            - 'autoendpoint.service'
        - src: 'autopush/autopush-egress.network'
          dest: 'autopush-egress.network'
          restart_units:
            - 'autoconnect.service'
            - 'autoendpoint.service'
        - src: 'autopush/autopush-valkey.network'
          dest: 'autopush-valkey.network'
          restart_units:
            - 'autopush-valkey.service'
            - 'autoconnect.service'
            - 'autoendpoint.service'
        - src: 'autopush/autopush-valkey.container'
          dest: 'autopush-valkey.container'
          restart_units:
            - 'autopush-valkey.service'
        - src: 'autopush/autoconnect.container'
          dest: 'autoconnect.container'
          restart_units:
            - 'autoconnect.service'
        - src: 'autopush/autoconnect.build'
          dest: 'autoconnect.build'
          restart_units:
            - 'autoconnect.service'
        - src: 'autopush/autoconnect.containerfile'
          dest: 'autoconnect.containerfile'
          restart_units:
            - 'autoconnect.service'
        - src: 'autopush/autoendpoint.container'
          dest: 'autoendpoint.container'
          restart_units:
            - 'autoendpoint.service'
        - src: 'autopush/autoendpoint.build'
          dest: 'autoendpoint.build'
          restart_units:
            - 'autoendpoint.service'
        - src: 'autopush/autoendpoint.containerfile'
          dest: 'autoendpoint.containerfile'
          restart_units:
            - 'autoendpoint.service'
        - src: 'autopush/autoendpoint-sortkey-timestamp.patch'
          dest: 'autoendpoint-sortkey-timestamp.patch'
          restart_units:
            - 'autoendpoint.service'
      managed_files_extra: []
      secrets:
        - name: 'autopush_crypto_keys'
          restart_units:
            - 'autoconnect.service'
            - 'autoendpoint.service'
        - name: 'autopush_auth_keys'
          restart_units:
            - 'autoconnect.service'
            - 'autoendpoint.service'
      volumes:
        - name: 'autopush-valkey'
          uid: '300012'
          gid: '300012'
      local_images:
        - 'localhost/autoconnect:latest'
        - 'localhost/autoendpoint:latest'
      certificates:
        - domains:
            - 'push.napiany.com'
            - 'updates.push.napiany.com'
  ansible.builtin.set_fact:
    podman_service_manifests: '{{ (podman_service_manifests | default({})) | combine({''autopush'': autopush_manifest}, recursive=true) }}'
