server {
    listen 443 ssl;
    include snippets/proxy-protocol-listener.conf;
    listen [::]:443 ssl;

    http2 on;

    server_name seedvault.napiany.com;

    ssl_certificate /etc/letsencrypt/consumers/nginx/seedvault.napiany.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/consumers/nginx/seedvault.napiany.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/consumers/nginx/seedvault.napiany.com/chain.pem;

    include snippets/universal_paths.conf;
    include snippets/security.conf;
    include snippets/permissions.conf;
    include snippets/proxy.conf;
    include snippets/robots.conf;

    client_max_body_size 0;
    proxy_request_buffering off;
    proxy_buffering off;

    location / {
        set $upstream_seedvault http://10.89.110.2:8080;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_pass $upstream_seedvault;
    }
}
