ServerName seedvault.napiany.com
ServerTokens Prod
ServerSignature Off
TraceEnable off
Timeout 3600
PidFile /tmp/httpd.pid
Mutex default:/tmp
DavLockDB /tmp/DavLock

<Directory "/data">
    AllowOverride None
    Options Indexes
    Require all granted
</Directory>

<LocationMatch "^/(?!pixel8pro(?:/|$)|pixel8a(?:/|$))">
    Require all denied
</LocationMatch>

<Location "/pixel8pro">
    DAV On
    DirectorySlash Off
    AuthType Basic
    AuthName "SeedVault Backups"
    AuthUserFile "/config/htpasswd"
    Require user pixel8pro
</Location>

<Location "/pixel8a">
    DAV On
    DirectorySlash Off
    AuthType Basic
    AuthName "SeedVault Backups"
    AuthUserFile "/config/htpasswd"
    Require user pixel8a
</Location>
