---
- name: 'Disable coredumps in /etc/security'
  block:
    - name: 'Ensure /etc/security/limits.d exists'
      ansible.builtin.file:
        dest: '/etc/security/limits.d'
        state: 'directory'
        owner: 'root'
        group: 'root'
        mode: '0755'

    - name: 'Disable coredumps in /etc/security'
      ansible.builtin.copy:
        owner: 'root'
        group: 'root'
        mode: '0644'
        content: '* hard core 0'
        dest: '/etc/security/limits.d/30-disable-coredump.conf'

- name: 'Disable coredumps in systemd'
  block:
    - name: 'Ensure /etc/systemd/coredump.conf.d exists'
      ansible.builtin.file:
        dest: '/etc/systemd/coredump.conf.d'
        state: 'directory'
        owner: 'root'
        group: 'root'
        mode: '0755'

    - name: 'Copy coredump override config file'
      ansible.builtin.copy:
        owner: 'root'
        group: 'root'
        mode: '0644'
        src: 'external/metropolis-nexus/coredump-disable.conf'
        dest: '/etc/systemd/coredump.conf.d/disable.conf'

- name: 'Mask kdump.service'
  ansible.builtin.systemd:
    name: 'kdump.service'
    enabled: false
    masked: true
