---
- name: 'Disable coredumps in /etc/security'
  block:
    - name: 'Ensure /etc/security/limits.d exists'
      ansible.builtin.file:
        dest: '/etc/security/limits.d'
        state: 'directory'

    - name: 'Disable coredumps in /etc/security'
      ansible.builtin.copy:
        content: '* hard core 0'
        dest: '/etc/security/limits.d/30-disable-coredump.conf'

- name: 'Disable coredumps in systemd'
  block:
    - name: 'Ensure /etc/systemd/coredump.conf.d exists'
      ansible.builtin.file:
        dest: '/etc/systemd/coredump.conf.d'
        state: 'directory'

    - name: 'Download coredump override config file'
      ansible.builtin.get_url:
        url: 'https://github.com/Metropolis-nexus/Common-Files/raw/refs/heads/main/etc/systemd/coredump.conf.d/disable.conf'
        dest: '/etc/systemd/coredump.conf.d/disable.conf'
        checksum: 'sha256:6f60b705a20ad895f0df031fb3c94e0886edc649beb2b2df4c6718eea84df10c'

- name: 'Mask kdump.service'
  ansible.builtin.systemd:
    name: 'kdump.service'
    enabled: false
    masked: true
