---
- name: 'Include chrony hardening tasks'
  ansible.builtin.include_tasks: 'chrony.yaml'

- name: 'Include coredump hardening tasks'
  ansible.builtin.include_tasks: 'coredump.yaml'

- name: 'Include Flatpak hardening tasks'
  ansible.builtin.include_tasks: 'flatpak.yaml'
  when: "'desktops' in group_names"

- name: 'Include fwupd hardening tasks'
  ansible.builtin.include_tasks: 'fwupd.yaml'
  when: "ansible_facts['virtualization_role'] == 'host'"

- name: 'Include kernel hardening tasks'
  ansible.builtin.include_tasks: 'kernel.yaml'

- name: 'Include NetworkManager hardening tasks'
  ansible.builtin.include_tasks: 'networkmanager.yaml'

- name: 'Include SSH hardening tasks'
  ansible.builtin.include_tasks: 'ssh.yaml'
  when: "'servers' in group_names"

- name: 'Mask debug-shell.service'
  ansible.builtin.systemd:
    name: 'debug-shell.service'
    enabled: false
    masked: true

- name: 'Remove nullok from /etc/pam.d/common-password-pc'
  ansible.builtin.replace:
    path: '/etc/pam.d/common-password-pc'
    regexp: '\s+nullok'
    replace: ''
    backup: true
