---
- name: 'Register Vaultwarden service manifest'
  vars:
    vaultwarden_manifest:
      quadlet_files:
        - src: 'vaultwarden/vaultwarden-egress.network'
          dest: 'vaultwarden-egress.network'
          restart_units:
            - 'vaultwarden.service'
        - src: 'vaultwarden/haproxy-vaultwarden.network'
          dest: 'haproxy-vaultwarden.network'
          restart_units:
            - 'haproxy.service'
            - 'vaultwarden.service'
        - src: 'vaultwarden/vaultwarden-postgres.network'
          dest: 'vaultwarden-postgres.network'
          restart_units:
            - 'vaultwarden-postgres.service'
            - 'vaultwarden.service'
        - src: 'vaultwarden/vaultwarden-postgres.container'
          dest: 'vaultwarden-postgres.container'
          restart_units:
            - 'vaultwarden-postgres.service'
      managed_files_extra:
        - 'vaultwarden.container'
      secrets:
        - name: 'vaultwarden-postgres_password'
          value_var: 'vault_podman_secret_vaultwarden_postgres_password'
          restart_units:
            - 'vaultwarden-postgres.service'
            - 'vaultwarden.service'
      volumes:
        - name: 'vaultwarden-postgres'
          uid: '300004'
          gid: '300004'
        - name: 'vaultwarden'
          uid: '300003'
          gid: '300003'
      local_images: []
      certificates:
        - domains:
            - 'vault.napiany.com'
  ansible.builtin.set_fact:
    podman_service_manifests: '{{ (podman_service_manifests | default({})) | combine({''vaultwarden'': vaultwarden_manifest}, recursive=true) }}'
