---
- name: 'Set ContainerCVE values'
  ansible.builtin.set_fact:
    containercve_quadlets:
      - src: 'containercve/haproxy-containercve.network'
        dest: 'haproxy-containercve.network'
        restart_units:
          - 'haproxy.service'
          - 'containercve.service'
      - src: 'containercve/containercve.container'
        dest: 'containercve.container'
        restart_units:
          - 'containercve.service'

- name: 'Copy ContainerCVE Quadlets'
  ansible.builtin.include_tasks: 'service_task.yaml'
  vars:
    podman_service_task: 'quadlets'
    podman_quadlet_files: '{{ containercve_quadlets }}'

- name: 'Create the ContainerCVE volume'
  ansible.builtin.include_tasks: 'service_task.yaml'
  vars:
    podman_service_task: 'volume'
    podman_volume:
      name: 'containercve'
      uid: '300005'
      gid: '300005'

- name: 'Issue the ContainerCVE certificate'
  ansible.builtin.include_tasks: 'service_task.yaml'
  vars:
    podman_service_task: 'certificate'
    podman_certificate:
      domains:
        - 'containercve.com'

- name: 'Start ContainerCVE'
  ansible.builtin.systemd:
    name: 'containercve.service'
    state: 'started'
    enabled: true
    daemon_reload: true
