---
- name: 'Copy {{ podman_quadlet_files_label | default("Quadlet") }} files'
  ansible.builtin.copy:
    src: '{{ podman_quadlet_file.src }}'
    dest: '/etc/containers/systemd/{{ podman_quadlet_file.dest }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ podman_quadlet_files }}'
  loop_control:
    loop_var: 'podman_quadlet_file'
    label: '{{ podman_quadlet_file.dest }}'
  register: 'podman_quadlet_copy_results'
  notify: '{{ (podman_quadlet_file.notify | default([])) + (["Recreate changed Podman networks"] if (podman_quadlet_file.dest is match(".*\\.network$")) else []) }}'

- name: 'Track changed Podman network Quadlet files'
  ansible.builtin.set_fact:
    podman_changed_networks: '{{ ((podman_changed_networks | default([])) + (podman_quadlet_copy_results.results | default([]) | selectattr("changed") | map(attribute="dest") | map("basename") | select("match", ".*\.network$") | map("regex_replace", "\.network$", "") | list)) | unique }}'
  when:
    - '((podman_quadlet_copy_results.results | default([]) | selectattr("changed") | map(attribute="dest") | map("basename") | select("match", ".*\.network$") | list | length) > 0)'
