---
- name: 'Set Kanidm domain facts'
  vars:
    kanidm_settings_candidate: '{{ (podman_services | default({})).get("kanidm", {}) }}'
  ansible.builtin.set_fact:
    kanidm_domain: '{{ kanidm_settings_candidate.domain | default("") }}'

- name: 'Ensure Kanidm domain config is defined'
  ansible.builtin.assert:
    that:
      - 'kanidm_domain | length > 0'
    fail_msg: 'Missing podman_services.kanidm.domain for the Kanidm host.'

- name: 'Copy nginx-kanidm.network'
  ansible.builtin.copy:
    src: 'kanidm/nginx-kanidm.network'
    dest: '/etc/containers/systemd/nginx-kanidm.network'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Daemon reload'
    - 'Restart nginx'
    - 'Restart kanidm'

- name: 'Copy kanidm.container'
  ansible.builtin.copy:
    src: 'kanidm/kanidm.container'
    dest: '/etc/containers/systemd/kanidm.container'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Daemon reload'
    - 'Restart kanidm'

- name: 'Template server.toml to kanidm volume'
  block:
    - name: 'Create kanidm volume'
      ansible.builtin.command:
        cmd: 'podman volume create kanidm'
      register: 'kanidm_volume_create'
      changed_when: 'kanidm_volume_create.rc == 0'
      failed_when:
        - 'kanidm_volume_create.rc != 0'
        - '''already exists'' not in kanidm_volume_create.stderr'

    - name: 'Get kanidm volume mount point'
      ansible.builtin.command:
        argv:
          - 'podman'
          - 'volume'
          - 'inspect'
          - 'kanidm'
          - '--format'
          - '{{ "{{.Mountpoint}}" }}'
      register: 'kanidm_mountpoint'
      changed_when: false
      failed_when: 'not ansible_check_mode and kanidm_mountpoint.rc != 0'
      check_mode: false

    - name: 'Set kanidm volume ownership'
      ansible.builtin.file:
        path: '{{ kanidm_mountpoint.stdout }}'
        owner: '300002'
        group: '300002'
        mode: '0700'
      when: 'kanidm_mountpoint.stdout | default("") | trim | length > 0'

    - name: 'Template server.toml'
      ansible.builtin.template:
        src: 'kanidm/server.toml.j2'
        dest: '{{ kanidm_mountpoint.stdout }}/server.toml'
        owner: '300002'
        group: '300002'
        mode: '0600'
      when: 'kanidm_mountpoint.stdout | default("") | trim | length > 0'
      notify:
        - 'Restart kanidm'

- name: 'Ensure Kanidm certificate is issued'
  ansible.builtin.include_tasks: 'issue_certificate.yaml'
  vars:
    certbot_certificate:
      domains:
        - '{{ kanidm_domain }}'
  when: 'not ansible_check_mode or certbot_mountpoint | default("") | trim | length > 0'

- name: 'Enable and start kanidm.service'
  ansible.builtin.systemd:
    name: 'kanidm.service'
    state: 'started'
    enabled: true
    daemon_reload: true

- name: 'Template nginx config to nginx-conf volume'
  block:
    - name: 'Get nginx-conf volume mount point'
      ansible.builtin.command:
        argv:
          - 'podman'
          - 'volume'
          - 'inspect'
          - 'nginx-conf'
          - '--format'
          - '{{ "{{.Mountpoint}}" }}'
      register: 'nginx_conf_mountpoint'
      changed_when: false
      failed_when: 'not ansible_check_mode and nginx_conf_mountpoint.rc != 0'
      check_mode: false

    - name: 'Template kanidm nginx config'
      ansible.builtin.template:
        src: 'kanidm/kanidm.conf.j2'
        dest: '{{ nginx_conf_mountpoint.stdout }}/kanidm.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
      when: 'nginx_conf_mountpoint.stdout | default("") | trim | length > 0'
      notify:
        - 'Restart nginx'
