---
- name: 'Set Kanidm values'
  vars:
    kanidm_settings: '{{ (podman_services | default({})).get("kanidm", {}) }}'
  ansible.builtin.set_fact:
    kanidm_domain: '{{ kanidm_settings.domain | default("") }}'
    kanidm_quadlets:
      - src: 'kanidm/haproxy-kanidm.network'
        dest: 'haproxy-kanidm.network'
        restart_units:
          - 'haproxy.service'
          - 'kanidm.service'
      - src: 'kanidm/kanidm.container'
        dest: 'kanidm.container'
        restart_units:
          - 'kanidm.service'

- name: 'Copy Kanidm Quadlets'
  ansible.builtin.include_tasks: 'service_task.yaml'
  vars:
    podman_service_task: 'quadlets'
    podman_quadlet_files: '{{ kanidm_quadlets }}'

- name: 'Create the Kanidm volume'
  ansible.builtin.include_tasks: 'service_task.yaml'
  vars:
    podman_service_task: 'volume'
    podman_volume:
      name: 'kanidm'
      uid: '300002'
      gid: '300002'

- name: 'Render the Kanidm config'
  ansible.builtin.template:
    src: 'kanidm/server.toml.j2'
    dest: '{{ podman_volume_mountpoints.kanidm }}/server.toml'
    owner: '300002'
    group: '300002'
    mode: '0600'
  register: 'kanidm_server_config'
  when: '(podman_volume_mountpoints | default({})).get("kanidm", "") | length > 0'

- name: 'Track Kanidm restart after config changes'
  ansible.builtin.include_tasks: 'service_task.yaml'
  vars:
    podman_service_task: 'track_units'
    podman_restart_units:
      - 'kanidm.service'
  when:
    - 'kanidm_server_config is defined'
    - 'kanidm_server_config.changed | default(false)'

- name: 'Issue the Kanidm certificate'
  ansible.builtin.include_tasks: 'service_task.yaml'
  vars:
    podman_service_task: 'certificate'
    podman_certificate:
      domains:
        - '{{ kanidm_domain }}'
      restart_units:
        - 'kanidm.service'
  when: 'kanidm_domain | length > 0'

- name: 'Start Kanidm'
  ansible.builtin.systemd:
    name: 'kanidm.service'
    state: 'started'
    enabled: true
    daemon_reload: true
