---
- name: 'Manage podman secret {{ podman_secret.name }}'
  block:
    - name: 'Set podman secret value'
      ansible.builtin.set_fact:
        podman_secret_value: '{{ podman_secret.value if ''value'' in podman_secret else lookup("vars", podman_secret.value_var) }}'
      no_log: true

    - name: 'Set podman secret checksum'
      ansible.builtin.set_fact:
        podman_secret_checksum: '{{ podman_secret_value | hash("sha256") }}'
      no_log: true

    - name: 'Inspect existing podman secret'
      ansible.builtin.command:
        argv:
          - 'podman'
          - 'secret'
          - 'inspect'
          - '{{ podman_secret.name }}'
      register: 'podman_secret_inspect'
      changed_when: false
      failed_when: false

    - name: 'Set current podman secret checksum'
      ansible.builtin.set_fact:
        podman_secret_current_checksum: ''

    - name: 'Read current podman secret checksum'
      ansible.builtin.set_fact:
        podman_secret_current_checksum: "{{ ((podman_secret_inspect.stdout | from_json | first).Spec.Labels | default({})).get('ansible-sha256', '') }}"
      when:
        - 'podman_secret_inspect.rc == 0'
        - 'podman_secret_inspect.stdout | trim | length > 0'

    - name: 'Create or rotate podman secret'
      ansible.builtin.command:
        argv:
          - 'podman'
          - 'secret'
          - 'create'
          - '--replace'
          - '--label'
          - 'managed-by=ansible'
          - '--label'
          - 'ansible-sha256={{ podman_secret_checksum }}'
          - '{{ podman_secret.name }}'
          - '-'
        stdin: '{{ podman_secret_value }}'
        stdin_add_newline: false
      when: 'podman_secret_current_checksum != podman_secret_checksum'
      changed_when: true
      notify:
        - 'Try restart podman secret consumers'
      no_log: true
