---
- name: 'Include nginx fact tasks'
  ansible.builtin.include_tasks: 'nginx/facts.yaml'

- name: 'Include nginx edge and unit tasks'
  ansible.builtin.include_tasks: 'nginx/edge_and_units.yaml'

- name: 'Include nginx volume and image tasks'
  ansible.builtin.include_tasks: 'nginx/volumes_and_images.yaml'

- name: 'Include nginx service tasks'
  ansible.builtin.include_tasks: 'nginx/services.yaml'
