---
- name: 'Include storage tasks'
  ansible.builtin.include_tasks:
    file: 'storage.yaml'
    apply:
      tags:
        - 'miniserver'
        - 'storage'
  tags:
    - 'miniserver'
    - 'storage'
