server {
    listen 443 ssl;
    listen 8443 ssl proxy_protocol;
    listen [::]:443 ssl;

    server_name mollysocket.napiany.com;

    ssl_certificate /etc/letsencrypt/live/mollysocket.napiany.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mollysocket.napiany.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/mollysocket.napiany.com/chain.pem;

    include snippets/universal_paths.conf;
    include snippets/permissions.conf;
    include snippets/robots.conf;

    resolver 10.89.105.1 valid=30s ipv6=off;

    location / {
        set $upstream_mollysocket http://mollysocket:8020;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Original-URL $uri;
        proxy_pass $upstream_mollysocket;
    }
}
