server {
    listen 443 ssl;
    include snippets/proxy-protocol-listener.conf;
    listen [::]:443 ssl;

    http2 on;

    server_name mollysocket.napiany.com;

    ssl_certificate /etc/letsencrypt/consumers/nginx/mollysocket.napiany.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/consumers/nginx/mollysocket.napiany.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/consumers/nginx/mollysocket.napiany.com/chain.pem;

    include snippets/universal_paths.conf;
    include snippets/permissions.conf;
    include snippets/proxy.conf;
    include snippets/robots.conf;

    location / {
        set $upstream_mollysocket http://10.89.105.2:8020;
        proxy_pass $upstream_mollysocket;
    }
}
