---
- name: 'Set Kanidm values'
  ansible.builtin.set_fact:
    kanidm_domain: '{{ (podman_service_manifests.kanidm | default({})).domain | default('''') }}'

- name: 'Copy Kanidm Quadlets'
  ansible.builtin.include_tasks: 'helpers/quadlets.yaml'
  vars:
    podman_quadlet_files: '{{ (podman_service_manifests.kanidm | default({})).quadlet_files | default([]) }}'

- name: 'Render kanidm.container'
  ansible.builtin.template:
    src: 'kanidm/kanidm.container.j2'
    dest: '/etc/containers/systemd/kanidm.container'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: 'kanidm_container_unit'
  notify:
    - 'Daemon reload'

- name: 'Track Kanidm restart after unit changes'
  ansible.builtin.include_tasks: 'helpers/restart_units.yaml'
  vars:
    podman_restart_units:
      - 'kanidm.service'
  when: 'kanidm_container_unit.changed | default(false)'

- name: 'Create the Kanidm volume'
  ansible.builtin.include_tasks: 'helpers/volume.yaml'
  vars:
    podman_volume: '{{ ((podman_service_manifests.kanidm | default({})).volumes | default([]) | first) }}'

- name: 'Render the Kanidm config'
  ansible.builtin.template:
    src: 'kanidm/server.toml.j2'
    dest: '{{ podman_volume_mountpoints.kanidm }}/server.toml'
    owner: '300002'
    group: '300002'
    mode: '0600'
  register: 'kanidm_server_config'
  when: '(podman_volume_mountpoints | default({})).get(''kanidm'', '''') | length > 0'

- name: 'Track Kanidm restart after config changes'
  ansible.builtin.include_tasks: 'helpers/restart_units.yaml'
  vars:
    podman_restart_units:
      - 'kanidm.service'
  when:
    - 'kanidm_server_config is defined'
    - 'kanidm_server_config.changed | default(false)'

- name: 'Issue the Kanidm certificate'
  ansible.builtin.include_tasks: 'helpers/certificate.yaml'
  vars:
    podman_certificate: '{{ ((podman_service_manifests.kanidm | default({})).certificates | default([]) | first) }}'
  when: '((podman_service_manifests.kanidm | default({})).certificates | default([]) | length) > 0'

- name: 'Start Kanidm'
  ansible.builtin.systemd:
    name: 'kanidm.service'
    state: 'started'
    enabled: true
    daemon_reload: true
