---
- name: 'Register Kanidm service manifest'
  vars:
    kanidm_settings: '{{ (podman_services | default({})).get(''kanidm'', {}) }}'
    kanidm_domain: '{{ kanidm_settings.domain | default('''') }}'
    kanidm_vaultwarden_quadlet_files: '{{ [{''src'': ''vaultwarden/kanidm-vaultwarden.network'', ''dest'': ''kanidm-vaultwarden.network'', ''restart_units'': [''kanidm.service'', ''vaultwarden.service'']}] if (''vaultwarden'' in (podman_containers_selected | default([]))) else [] }}'
    kanidm_monitoring_quadlet_files: '{{ [{''src'': ''monitoring/kanidm-grafana.network'', ''dest'': ''kanidm-grafana.network'', ''restart_units'': [''kanidm.service'', ''grafana.service'']}] if (''monitoring'' in (podman_containers_selected | default([]))) else [] }}'
    kanidm_shared_network_quadlet_files: '{{ kanidm_vaultwarden_quadlet_files + kanidm_monitoring_quadlet_files }}'
    kanidm_manifest:
      domain: '{{ kanidm_domain }}'
      quadlet_files: '{{ [{''src'': ''kanidm/haproxy-kanidm.network'', ''dest'': ''haproxy-kanidm.network'', ''restart_units'': [''haproxy.service'', ''kanidm.service'']}] + kanidm_shared_network_quadlet_files }}'
      managed_files_extra:
        - 'kanidm.container'
      secrets: []
      volumes:
        - name: 'kanidm'
          uid: '300002'
          gid: '300002'
      local_images: []
      certificates: '{{ [{''domains'': [kanidm_domain], ''restart_units'': [''kanidm.service'']}] if (kanidm_domain | length > 0) else [] }}'
  ansible.builtin.set_fact:
    podman_service_manifests: '{{ (podman_service_manifests | default({})) | combine({''kanidm'': kanidm_manifest}, recursive=true) }}'
