---
- name: 'Reload gateway systemd'
  ansible.builtin.systemd:
    daemon_reload: true

- name: 'Restart gateway wireguard'
  ansible.builtin.systemd:
    name: 'wg-quick@wg0.service'
    state: 'restarted'
    enabled: true

- name: 'Restart gateway crowdsec-firewall-bouncer'
  ansible.builtin.systemd:
    name: 'crowdsec-firewall-bouncer.service'
    state: 'restarted'
    enabled: true
