---
- name: 'Set Stalwart values'
  ansible.builtin.set_fact:
    stalwart_certificate_blocks: '{{ (podman_service_manifests.stalwart | default({})).certificate_blocks | default([]) }}'
    stalwart_primary_domain: '{{ (podman_service_manifests.stalwart | default({})).primary_domain | default('''') }}'

- name: 'Manage Stalwart secrets'
  ansible.builtin.include_tasks: 'helpers/secret.yaml'
  vars:
    podman_secret: '{{ item }}'
  loop: '{{ (podman_service_manifests.stalwart | default({})).secrets | default([]) }}'
  loop_control:
    label: '{{ item.name }}'

- name: 'Copy Stalwart Quadlets'
  ansible.builtin.include_tasks: 'helpers/quadlets.yaml'
  vars:
    podman_quadlet_files: '{{ (podman_service_manifests.stalwart | default({})).quadlet_files | default([]) }}'

- name: 'Apply pending Podman network changes before starting Stalwart services'
  ansible.builtin.meta: 'flush_handlers'

- name: 'Create Stalwart volumes'
  ansible.builtin.include_tasks: 'helpers/volume.yaml'
  vars:
    podman_volume: '{{ item }}'
  loop: '{{ (podman_service_manifests.stalwart | default({})).volumes | default([]) }}'
  loop_control:
    label: '{{ item.name }}'

- name: 'Configure Stalwart'
  ansible.builtin.include_tasks: 'stalwart/config.yaml'

- name: 'Start Stalwart services'
  ansible.builtin.include_tasks: 'stalwart/runtime.yaml'

- name: 'Issue the Stalwart certificates'
  ansible.builtin.include_tasks: 'stalwart/certificates.yaml'
