---
- name: 'Manage MollySocket secrets'
  ansible.builtin.include_tasks: 'helpers/secret.yaml'
  vars:
    podman_secret: '{{ item }}'
  loop: '{{ (podman_service_manifests.mollysocket | default({})).secrets | default([]) }}'
  loop_control:
    label: '{{ item.name }}'

- name: 'Copy MollySocket Quadlets'
  ansible.builtin.include_tasks: 'helpers/quadlets.yaml'
  vars:
    podman_quadlet_files: '{{ (podman_service_manifests.mollysocket | default({})).quadlet_files | default([]) }}'

- name: 'Create the MollySocket volume'
  ansible.builtin.include_tasks: 'helpers/volume.yaml'
  vars:
    podman_volume: '{{ ((podman_service_manifests.mollysocket | default({})).volumes | default([]) | first) }}'

- name: 'Copy the MollySocket config'
  ansible.builtin.copy:
    src: 'mollysocket/config.toml'
    dest: '{{ podman_volume_mountpoints.mollysocket }}/config.toml'
    owner: '300009'
    group: '300009'
    mode: '0600'
  register: 'mollysocket_config_file'
  when: '(podman_volume_mountpoints | default({})).get(''mollysocket'', '''') | length > 0'

- name: 'Track MollySocket restart after config changes'
  ansible.builtin.include_tasks: 'helpers/restart_units.yaml'
  vars:
    podman_restart_units:
      - 'mollysocket.service'
  when:
    - 'mollysocket_config_file is defined'
    - 'mollysocket_config_file.changed | default(false)'

- name: 'Issue the MollySocket certificate'
  ansible.builtin.include_tasks: 'helpers/certificate.yaml'
  vars:
    podman_certificate: '{{ ((podman_service_manifests.mollysocket | default({})).certificates | default([]) | first) }}'
  when: '((podman_service_manifests.mollysocket | default({})).certificates | default([]) | length) > 0'

- name: 'Start MollySocket'
  ansible.builtin.systemd:
    name: 'mollysocket.service'
    state: 'started'
    enabled: true
    daemon_reload: true
