---
- name: 'Register MollySocket service manifest'
  vars:
    mollysocket_manifest:
      quadlet_files:
        - src: 'mollysocket/haproxy-mollysocket.network'
          dest: 'haproxy-mollysocket.network'
          restart_units:
            - 'haproxy.service'
            - 'mollysocket.service'
        - src: 'mollysocket/mollysocket.container'
          dest: 'mollysocket.container'
          restart_units:
            - 'mollysocket.service'
      managed_files_extra: []
      secrets:
        - name: 'mollysocket_vapid_privkey'
          value_var: 'vault_podman_secret_mollysocket_vapid_privkey'
          restart_units:
            - 'mollysocket.service'
        - name: 'mollysocket_allowed_uuids'
          value_var: 'vault_podman_secret_mollysocket_allowed_uuids'
          restart_units:
            - 'mollysocket.service'
      volumes:
        - name: 'mollysocket'
          uid: '300009'
          gid: '300009'
      local_images: []
      certificates:
        - domains:
            - 'mollysocket.napiany.com'
  ansible.builtin.set_fact:
    podman_service_manifests: '{{ (podman_service_manifests | default({})) | combine({''mollysocket'': mollysocket_manifest}, recursive=true) }}'
