---
- name: 'Manage Ente Postgres podman secret'
  ansible.builtin.include_tasks: 'helpers/secret.yaml'
  vars:
    podman_secret: '{{ ((podman_service_manifests.ente | default({})).secrets | default([]) | first) }}'
  no_log: true

- name: 'Copy Ente Quadlet files'
  ansible.builtin.include_tasks: 'helpers/quadlets.yaml'
  vars:
    podman_quadlet_files: '{{ (podman_service_manifests.ente | default({})).quadlet_files | default([]) }}'

- name: 'Prepare Ente volumes'
  ansible.builtin.include_tasks: 'ente/volumes.yaml'

- name: 'Configure Ente Garage'
  ansible.builtin.include_tasks: 'ente/garage.yaml'

- name: 'Configure Ente credentials'
  ansible.builtin.include_tasks: 'ente/credentials.yaml'

- name: 'Start Ente services'
  ansible.builtin.include_tasks: 'ente/runtime.yaml'
