---
- name: 'Enable and start ente-postgres.service'
  ansible.builtin.systemd:
    name: 'ente-postgres.service'
    state: 'started'
    enabled: true
    daemon_reload: true

- name: 'Issue the Ente certificate'
  ansible.builtin.include_tasks: 'helpers/certificate.yaml'
  vars:
    podman_certificate: '{{ ((podman_service_manifests.ente | default({})).certificates | default([]) | first) }}'
  when:
    - 'not ansible_check_mode or certbot_mountpoint | default('''') | trim | length > 0'
    - '((podman_service_manifests.ente | default({})).certificates | default([]) | length) > 0'

- name: 'Enable and start ente-museum.service'
  ansible.builtin.systemd:
    name: 'ente-museum.service'
    state: 'started'
    enabled: true
    daemon_reload: true

- name: 'Enable and start ente-web.service'
  ansible.builtin.systemd:
    name: 'ente-web.service'
    state: 'started'
    enabled: true
    daemon_reload: true
