---
- name: 'Prepare Ente Postgres volume'
  ansible.builtin.include_tasks: 'helpers/volume.yaml'
  vars:
    podman_volume: '{{ ((podman_service_manifests.ente | default({})).volumes | default([]) | selectattr(''name'', ''equalto'', ''ente-postgres'') | first) }}'

- name: 'Prepare Ente config volume'
  ansible.builtin.include_tasks: 'helpers/volume.yaml'
  vars:
    podman_volume: '{{ ((podman_service_manifests.ente | default({})).volumes | default([]) | selectattr(''name'', ''equalto'', ''ente-config'') | first) }}'

- name: 'Set Ente config volume mount point'
  ansible.builtin.set_fact:
    ente_config_mountpoint: '{{ (podman_volume_mountpoints | default({})).get(''ente-config'', '''') }}'

- name: 'Prepare Ente Garage config volume'
  ansible.builtin.include_tasks: 'helpers/volume.yaml'
  vars:
    podman_volume: '{{ ((podman_service_manifests.ente | default({})).volumes | default([]) | selectattr(''name'', ''equalto'', ''ente-garage-config'') | first) }}'

- name: 'Set Ente Garage config volume mount point'
  ansible.builtin.set_fact:
    ente_garage_config_mountpoint: '{{ (podman_volume_mountpoints | default({})).get(''ente-garage-config'', '''') }}'

- name: 'Prepare Ente Garage metadata volume'
  ansible.builtin.include_tasks: 'helpers/volume.yaml'
  vars:
    podman_volume: '{{ ((podman_service_manifests.ente | default({})).volumes | default([]) | selectattr(''name'', ''equalto'', ''ente-garage-meta'') | first) }}'
