---
- name: 'Manage Grid secrets'
  ansible.builtin.include_tasks: 'helpers/secret.yaml'
  vars:
    podman_secret: '{{ item }}'
  loop: '{{ (podman_service_manifests.grid | default({})).secrets | default([]) }}'
  loop_control:
    label: '{{ item.name }}'

- name: 'Copy Grid Quadlets'
  ansible.builtin.include_tasks: 'helpers/quadlets.yaml'
  vars:
    podman_quadlet_files: '{{ (podman_service_manifests.grid | default({})).quadlet_files | default([]) }}'

- name: 'Create Grid volumes'
  ansible.builtin.include_tasks: 'helpers/volume.yaml'
  vars:
    podman_volume: '{{ item }}'
  loop: '{{ (podman_service_manifests.grid | default({})).volumes | default([]) }}'
  loop_control:
    label: '{{ item.name }}'

- name: 'Configure Grid'
  ansible.builtin.include_tasks: 'grid/config.yaml'

- name: 'Start Grid services'
  ansible.builtin.include_tasks: 'grid/runtime.yaml'

- name: 'Issue the Grid certificate'
  ansible.builtin.include_tasks: 'helpers/certificate.yaml'
  vars:
    podman_certificate: '{{ ((podman_service_manifests.grid | default({})).certificates | default([]) | first) }}'
  when: '((podman_service_manifests.grid | default({})).certificates | default([]) | length) > 0'
