---
- name: 'Start Grid Postgres'
  ansible.builtin.systemd:
    name: 'grid-postgres.service'
    state: 'started'
    enabled: true
    daemon_reload: true

- name: 'Start Grid'
  ansible.builtin.systemd:
    name: 'grid.service'
    state: 'started'
    enabled: true
    daemon_reload: true
