---
podman_available_containers:
  - 'nginx'
  - 'haproxy'
  - 'kanidm'
  - 'grid'
  - 'ente'
  - 'vaultwarden'
  - 'containercve'
  - 'stalwart'
  - 'autopush'
  - 'mollysocket'

podman_reverse_proxy_containers:
  - 'kanidm'
  - 'grid'
  - 'ente'
  - 'vaultwarden'
  - 'containercve'
  - 'stalwart'
  - 'autopush'
  - 'mollysocket'

podman_edge_proxy_containers:
  - 'nginx'
  - 'haproxy'
