---
podman_available_containers:
  - 'haproxy'
  - 'kanidm'
  - 'grid'
  - 'ente'
  - 'vaultwarden'
  - 'seedvault'
  - 'containercve'
  - 'stalwart'
  - 'autopush'
  - 'mollysocket'

podman_stalwart_ipv4: '10.89.103.2'
podman_stalwart_ipv6: 'fd89:103::2'
podman_stalwart_gateway_egress_table: '252'
podman_wireguard_ipv6_prefix: 'fd66:66::'
podman_wireguard_gateway_ipv6: 'fd66:66::1'
podman_local_ingress_ipv6: ''
podman_local_source_ipv4_cidrs: []
podman_local_source_ipv6_cidrs: []
podman_crowdsec_ipv4: '10.89.106.2'
podman_crowdsec_ipv6: 'fd89:106::2'
podman_crowdsec_spoa_ipv4: '10.89.106.3'
podman_crowdsec_spoa_ipv6: 'fd89:106::3'
podman_haproxy_crowdsec_ipv4: '10.89.106.4'
podman_haproxy_crowdsec_ipv6: 'fd89:106::4'

podman_haproxy_networks:
  kanidm:
    resolver: '10.89.100.1'
    alias: 'kanidm'
    ipv4: '10.89.100.2'
    ipv6: 'fd89:100::2'
    proxy_ipv6: 'fd89:100::10'
  vaultwarden:
    resolver: '10.89.101.1'
    alias: 'vaultwarden'
    ipv4: '10.89.101.2'
    ipv6: 'fd89:101::2'
    proxy_ipv6: 'fd89:101::10'
  containercve:
    resolver: '10.89.102.1'
    alias: 'containercve'
    ipv4: '10.89.102.2'
    ipv6: 'fd89:102::2'
    proxy_ipv4: '10.89.102.10'
    proxy_ipv6: 'fd89:102::10'
  stalwart:
    resolver: '10.89.103.1'
    alias: 'stalwart'
    ipv4: '{{ podman_stalwart_ipv4 }}'
    ipv6: '{{ podman_stalwart_ipv6 }}'
    proxy_ipv6: 'fd89:103::10'
  autopush:
    resolver: '10.89.104.1'
    alias: 'autoconnect'
    secondary_alias: 'autoendpoint'
    ipv4: '10.89.104.2'
    ipv6: 'fd89:104::2'
    secondary_ipv4: '10.89.104.3'
    secondary_ipv6: 'fd89:104::3'
    proxy_ipv4: '10.89.104.10'
    proxy_ipv6: 'fd89:104::10'
  mollysocket:
    resolver: '10.89.105.1'
    alias: 'mollysocket'
    ipv4: '10.89.105.2'
    ipv6: 'fd89:105::2'
    proxy_ipv4: '10.89.105.10'
    proxy_ipv6: 'fd89:105::10'
  ente:
    resolver: '10.89.109.1'
    alias: 'ente-museum'
    ipv4: '10.89.109.2'
    ipv6: 'fd89:109::2'
    s3_alias: 'ente-garage'
    s3_ipv4: '10.89.109.3'
    s3_ipv6: 'fd89:109::3'
    web_alias: 'ente-web'
    web_ipv4: '10.89.109.4'
    web_ipv6: 'fd89:109::4'
    proxy_ipv6: 'fd89:109::10'
  grid:
    resolver: '10.89.108.1'
    alias: 'grid'
    ipv4: '10.89.108.2'
    ipv6: 'fd89:108::2'
    proxy_ipv6: 'fd89:108::10'
  seedvault:
    resolver: '10.89.110.1'
    alias: 'seedvault'
    ipv4: '10.89.110.2'
    ipv6: 'fd89:110::2'
    proxy_ipv6: 'fd89:110::10'
