server {
    listen 443 ssl;
    listen 8443 ssl proxy_protocol;
    listen [::]:443 ssl;

    http2 on;

    server_name push.napiany.com;

    ssl_certificate /etc/letsencrypt/live/push.napiany.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/push.napiany.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/push.napiany.com/chain.pem;

    include snippets/universal_paths.conf;
    include snippets/security.conf;
    include snippets/permissions.conf;
    include snippets/proxy.conf;
    include snippets/robots.conf;

    limit_conn_status 429;
    limit_req_status 429;
    limit_conn autopush_conn_per_ip 10;
    limit_req zone=autopush_req_per_ip burst=20 nodelay;

    resolver 10.89.104.1 valid=30s ipv6=off;

    location = /health {
        include snippets/local-ip-only.conf;
        set $upstream_autoconnect http://autoconnect:8080;
        proxy_buffering off;
        proxy_read_timeout 610s;
        proxy_send_timeout 60s;
        proxy_pass $upstream_autoconnect;
    }

    location = /__heartbeat__ {
        include snippets/local-ip-only.conf;
        set $upstream_autoconnect http://autoconnect:8080;
        proxy_buffering off;
        proxy_read_timeout 610s;
        proxy_send_timeout 60s;
        proxy_pass $upstream_autoconnect;
    }

    location = /__version__ {
        include snippets/local-ip-only.conf;
        set $upstream_autoconnect http://autoconnect:8080;
        proxy_buffering off;
        proxy_read_timeout 610s;
        proxy_send_timeout 60s;
        proxy_pass $upstream_autoconnect;
    }

    location / {
        set $upstream_autoconnect http://autoconnect:8080;
        proxy_buffering off;
        proxy_read_timeout 610s;
        proxy_send_timeout 60s;
        proxy_pass $upstream_autoconnect;
    }
}

server {
    listen 443 ssl;
    listen 8443 ssl proxy_protocol;
    listen [::]:443 ssl;

    http2 on;

    server_name updates.push.napiany.com;

    ssl_certificate /etc/letsencrypt/live/push.napiany.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/push.napiany.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/push.napiany.com/chain.pem;

    include snippets/universal_paths.conf;
    include snippets/security.conf;
    include snippets/permissions.conf;
    include snippets/proxy.conf;
    include snippets/robots.conf;

    limit_conn_status 429;
    limit_req_status 429;
    limit_conn autopush_conn_per_ip 20;
    limit_req zone=autopush_req_per_ip burst=40 nodelay;

    resolver 10.89.104.1 valid=30s ipv6=off;

    location = /health {
        include snippets/local-ip-only.conf;
        set $upstream_autoendpoint http://autoendpoint:8000;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
        proxy_pass $upstream_autoendpoint;
    }

    location = /__heartbeat__ {
        include snippets/local-ip-only.conf;
        set $upstream_autoendpoint http://autoendpoint:8000;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
        proxy_pass $upstream_autoendpoint;
    }

    location = /__version__ {
        include snippets/local-ip-only.conf;
        set $upstream_autoendpoint http://autoendpoint:8000;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
        proxy_pass $upstream_autoendpoint;
    }

    location / {
        set $upstream_autoendpoint http://autoendpoint:8000;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
        proxy_pass $upstream_autoendpoint;
    }
}
