server {
    listen 443 ssl;
    listen 8443 ssl proxy_protocol;
    listen [::]:443 ssl;

    server_name containercve.com;

    ssl_certificate /etc/letsencrypt/live/containercve.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/containercve.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/containercve.com/chain.pem;

    include snippets/universal_paths.conf;
    include snippets/security.conf;
    include snippets/permissions.conf;
    include snippets/cross-origin-security.conf;
    include snippets/proxy.conf;

    proxy_hide_header Content-Security-Policy;
    add_header Content-Security-Policy "default-src 'none'; script-src 'sha256-Jw6/Xad7U0tsgxWfyCIdipF6cR2QSY8da0PVW1YztVg=' 'sha256-sMQN0ivKSXn4CzbfctfuDwOLVQHzbHrf9DKYzVlcJWs='; style-src 'sha256-cNByiQgjaEOf3hPC5AgBGfG8FNkBmSfZMoP1lAxYGqo=' 'sha256-68zmB9dSOQFLut1tIRsm8/AkvU9Mk6uWLXDzcjcleyA=' 'sha256-iKtLdCjH63HrirR5Mj0AzskMBwKQ6Vayyx2dPEGh79A='; connect-src 'self'; img-src 'self' data:; font-src 'none'; frame-src 'none'; frame-ancestors 'none'; object-src 'none'; base-uri 'self'; form-action 'self'; manifest-src 'none'; worker-src 'none'; upgrade-insecure-requests; require-trusted-types-for 'script'; trusted-types containercve;" always;

    resolver 10.89.102.1 valid=30s ipv6=off;

    location ~ ^/scan {
        proxy_hide_header X-Robots-Tag;
        add_header X-Robots-Tag 'noindex' always;

        include snippets/security.conf;
        include snippets/permissions.conf;
        include snippets/cross-origin-security.conf;
        include snippets/proxy.conf;
        proxy_hide_header Content-Security-Policy;
        add_header Content-Security-Policy "default-src 'none'; script-src 'sha256-Jw6/Xad7U0tsgxWfyCIdipF6cR2QSY8da0PVW1YztVg=' 'sha256-sMQN0ivKSXn4CzbfctfuDwOLVQHzbHrf9DKYzVlcJWs='; style-src 'sha256-cNByiQgjaEOf3hPC5AgBGfG8FNkBmSfZMoP1lAxYGqo=' 'sha256-68zmB9dSOQFLut1tIRsm8/AkvU9Mk6uWLXDzcjcleyA=' 'sha256-iKtLdCjH63HrirR5Mj0AzskMBwKQ6Vayyx2dPEGh79A='; connect-src 'self'; img-src 'self' data:; font-src 'none'; frame-src 'none'; frame-ancestors 'none'; object-src 'none'; base-uri 'self'; form-action 'self'; manifest-src 'none'; worker-src 'none'; upgrade-insecure-requests; require-trusted-types-for 'script'; trusted-types containercve;" always;

        set $upstream_containercve http://containercve:8080;
        proxy_pass $upstream_containercve;
    }

    location /api/scan {
        proxy_read_timeout 600s;

        set $upstream_containercve http://containercve:8080;
        proxy_pass $upstream_containercve;
    }

    location / {
        set $upstream_containercve http://containercve:8080;
        proxy_pass $upstream_containercve;
    }
}
